<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>ZSnaper</AssemblyName>
    <RootNamespace>ZSnaper</RootNamespace>
    <Version>0.0.5-beta</Version>
    <InformationalVersion>0.0.5-beta</InformationalVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>assets\logo\ZSnaper.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="src\Plugin.Abstractions\**" />
    <Compile Remove="installer\**" />
    <Compile Remove="samples\**" />
    <ProjectReference Include="src\Plugin.Abstractions\ZSnaper.Plugin.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\logo\ZSnaper.ico">
      <LogicalName>ZSnaper.Assets.Logo.ZSnaper.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="assets\logo\ZSnaper-dark.ico">
      <LogicalName>ZSnaper.Assets.Logo.ZSnaper-dark.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="assets\logo\icon-light.svg">
      <LogicalName>ZSnaper.Assets.Logo.icon-light.svg</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="assets\logo\icon-dark.svg">
      <LogicalName>ZSnaper.Assets.Logo.icon-dark.svg</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="assets\lucide\*.svg">
      <LogicalName>ZSnaper.Assets.Lucide.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="2.88.9" />
    <PackageReference Include="SharpHook" Version="7.1.3" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WPF" />
  </ItemGroup>

</Project>
